name: Deploy para InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do GitHub
        uses: actions/checkout@v4

      - name: Enviar arquivos para o InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.INFINITY_FTP_SERVER }}
          username: ${{ secrets.INFINITY_FTP_USERNAME }}
          password: ${{ secrets.INFINITY_FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
